In [37]:
import pandas as pd
import numpy as np

In [38]:
starting_elo_df = pd.read_csv("starting_elo.csv")

In [39]:
df = pd.read_csv("cleaned_data.csv", index_col=0)

In [40]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating
0,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,90.0480,0.400000,0.144367,0.333333,0.222222,93.283582,104.388770,-11.105188
1,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,88.0128,0.500000,0.238602,0.461538,0.278481,106.802647,95.440663,11.361984
2,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,92.4672,0.560000,0.173034,0.184211,0.373333,115.716708,129.775748,-14.059039
3,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,92.2368,0.594937,0.086733,0.128205,0.405063,130.099917,116.005759,14.094158
4,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,92.0832,0.500000,0.130317,0.225000,0.211765,107.511468,98.823673,8.687795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33489,42500316,2026-05-28 20:30:00,Spurs,1610612759,1,1.0,118,91,96.0000,0.551136,0.125000,0.268293,0.284091,122.916667,94.791667,28.125000
33490,42500317,2026-05-30 20:00:00,Spurs,1610612759,0,1.0,111,103,89.6256,0.551136,0.133890,0.348837,0.215909,123.848543,114.922522,8.926021
33491,42500317,2026-05-30 20:00:00,Thunder,1610612760,1,0.0,103,111,91.8528,0.518072,0.141531,0.285714,0.265060,112.135939,120.845527,-8.709588
33492,42500401,2026-06-03 20:30:00,Knicks,1610612752,0,1.0,105,95,95.9232,0.473404,0.083400,0.200000,0.191489,109.462570,99.037563,10.425007
33493,42500401,2026-06-03 20:30:00,Spurs,1610612759,1,0.0,95,105,95.0400,0.421348,0.136785,0.264151,0.280899,99.957912,110.479798,-10.521886

In [41]:
elo_container = starting_elo_df.iloc[0].to_dict()

In [42]:
elo_container

{'Wizards': 1450.8339,
 'Cavaliers': 1346.9901,
 'Lakers': 1555.7339,
 'Mavericks': 1519.9543,
 'Celtics': 1592.0532,
 'Heat': 1660.3782,
 'Kings': 1417.2316,
 'Bulls': 1596.7417,
 'Pistons': 1430.9758,
 'Rockets': 1501.2556,
 'Grizzlies': 1578.983,
 'Clippers': 1560.9281,
 'Spurs': 1676.2136,
 'Pelicans': 1453.0475,
 '76ers': 1537.5059,
 'Nuggets': 1576.3953,
 'Suns': 1530.1812,
 'Warriors': 1421.1807,
 'Trail Blazers': 1450.6614,
 'Pacers': 1561.7098,
 'Raptors': 1437.3424,
 'Jazz': 1532.3057,
 'Thunder': 1659.13,
 'Hawks': 1545.6381,
 'Bucks': 1501.167,
 'Hornets': 1240.0372,
 'Timberwolves': 1411.7732,
 'Knicks': 1529.618,
 'Magic': 1478.0159,
 'Nets': 1371.431}

In [43]:
df["gameDateTimeEst"] = pd.to_datetime(df["gameDateTimeEst"])

In [44]:
def season_column(df):
    df["season"] = np.where(df["gameDateTimeEst"].dt.month >= 10, df["gameDateTimeEst"].dt.year + 1, df["gameDateTimeEst"].dt.year)
    return df

In [45]:
df = season_column(df)
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating,season
0,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,90.0480,0.400000,0.144367,0.333333,0.222222,93.283582,104.388770,-11.105188,2013
1,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,88.0128,0.500000,0.238602,0.461538,0.278481,106.802647,95.440663,11.361984,2013
2,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,92.4672,0.560000,0.173034,0.184211,0.373333,115.716708,129.775748,-14.059039,2013
3,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,92.2368,0.594937,0.086733,0.128205,0.405063,130.099917,116.005759,14.094158,2013
4,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,92.0832,0.500000,0.130317,0.225000,0.211765,107.511468,98.823673,8.687795,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33489,42500316,2026-05-28 20:30:00,Spurs,1610612759,1,1.0,118,91,96.0000,0.551136,0.125000,0.268293,0.284091,122.916667,94.791667,28.125000,2026
33490,42500317,2026-05-30 20:00:00,Spurs,1610612759,0,1.0,111,103,89.6256,0.551136,0.133890,0.348837,0.215909,123.848543,114.922522,8.926021,2026
33491,42500317,2026-05-30 20:00:00,Thunder,1610612760,1,0.0,103,111,91.8528,0.518072,0.141531,0.285714,0.265060,112.135939,120.845527,-8.709588,2026
33492,42500401,2026-06-03 20:30:00,Knicks,1610612752,0,1.0,105,95,95.9232,0.473404,0.083400,0.200000,0.191489,109.462570,99.037563,10.425007,2026
33493,42500401,2026-06-03 20:30:00,Spurs,1610612759,1,0.0,95,105,95.0400,0.421348,0.136785,0.264151,0.280899,99.957912,110.479798,-10.521886,2026

In [46]:
def calculate_new_elo(old_elo, m, s, e, k=20):
    new_elo = old_elo + k * m * (s - e)

    return new_elo

In [47]:
def margin_of_victory(mov, elo_diff):
    m = ((mov + 3)**.8) / (7.5 + .006 * (elo_diff))
    
    return m

In [48]:
def off_season_regression(elo_container):
    for (team_name, current_elo) in elo_container.items():
        regressed_elo = (current_elo * .75) + (1505 * 0.25)

        elo_container[team_name] = regressed_elo
    return elo_container

In [49]:
def elo_calculation(df, elo_container):
    df = df.sort_values(by=["gameDateTimeEst", "gameId", "home"])
    pre_game_elos = []

    current_season = df["season"].iloc[0]
    for game_id, team_df in df.groupby("gameId", sort=False):

        game_season = team_df["season"].iloc[0]
        if current_season != game_season:
            off_season_regression(elo_container)
            current_season = game_season


        if len(team_df) != 2:
            continue


        home_row = team_df[team_df["home"] == 1].iloc[0]
        away_row = team_df[team_df["home"] == 0].iloc[0]

        home_name = home_row["teamName"]
        away_name = away_row["teamName"]

        home_pre = elo_container.get(home_name, 1500)
        away_pre = elo_container.get(away_name, 1500)

        pre_game_elos.extend([away_pre, home_pre])

        d = (home_pre + 100) - away_pre
        expected_home = 1 / (1 + 10 ** (-d / 400))
        expected_away = 1 - expected_home

        if home_row["win"] == 1:
            mov = home_row["points"] - home_row["opponentScore"]
            elo_diff = home_pre - away_pre
            home_s, away_s = 1, 0
        else:
            mov = away_row["points"] - away_row["opponentScore"]
            elo_diff = away_pre - home_pre
            home_s, away_s = 0, 1


        m = margin_of_victory(mov, elo_diff)

        home_post = calculate_new_elo(home_pre, m, home_s, expected_home)
        away_post = calculate_new_elo(away_pre, m, away_s, expected_away)


        elo_container[home_name] = home_post
        elo_container[away_name] = away_post

    df["pre_game_elo"] = pre_game_elos
    return df

In [50]:
df = elo_calculation(df, elo_container)

In [51]:
df.head()

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating,season,pre_game_elo
0,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,90.0480,0.400000,0.144367,0.333333,0.222222,93.283582,104.388770,-11.105188,2013,1450.8339
1,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,88.0128,0.500000,0.238602,0.461538,0.278481,106.802647,95.440663,11.361984,2013,1346.9901
2,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,92.4672,0.560000,0.173034,0.184211,0.373333,115.716708,129.775748,-14.059039,2013,1592.0532
3,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,92.2368,0.594937,0.086733,0.128205,0.405063,130.099917,116.005759,14.094158,2013,1660.3782
4,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,92.0832,0.500000,0.130317,0.225000,0.211765,107.511468,98.823673,8.687795,2013,1519.9543

In [52]:
df.to_csv("data_with_elo.csv")

In [53]:
# idx = df.groupby("season")["pre_game_elo"].idxmax()
# result_df = df.loc[idx, ["teamName", "pre_game_elo", "season"]]
# result_df.sort_values(by=["season"], ascending=[False])