In [29]:
# Code to get the data

In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/TeamStatistics.csv")

In [32]:
df.head()

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
0,42500302,2026-05-21 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 2,2.0,4.0,11.0,0.0,NaN,NaN,NaN,2026-05-21 20:00:00
1,42500302,2026-05-21 20:00:00,New York,Knicks,1610612752,Cleveland,Cavaliers,1610612739,1,1.0,...,East Conf. Finals,Game 2,2.0,3.0,14.0,2.0,NaN,NaN,NaN,2026-05-21 20:00:00
2,42500312,2026-05-20 20:30:00,San Antonio,Spurs,1610612759,Oklahoma City,Thunder,1610612760,0,0.0,...,West Conf. Finals,Game 2,2.0,2.0,4.0,0.0,NaN,NaN,NaN,2026-05-20 20:30:00
3,42500312,2026-05-20 20:30:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,1,1.0,...,West Conf. Finals,Game 2,2.0,1.0,9.0,1.0,NaN,NaN,NaN,2026-05-20 20:30:00
4,42500301,2026-05-19 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 1,1.0,4.0,17.0,2.0,3.0,NaN,3.0,2026-05-19 20:00:00

In [33]:
df.shape

(146536, 59)

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 146536 entries, 0 to 146535
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gameId                   146536 non-null  int64
 1   gameDateTimeEst          146536 non-null  str
 2   teamCity                 146520 non-null  str
 3   teamName                 146534 non-null  str
 4   teamId                   146536 non-null  int64
 5   opponentTeamCity         146520 non-null  str
 6   opponentTeamName         146534 non-null  str
 7   opponentTeamId           146536 non-null  int64
 8   home                     146536 non-null  int64
 9   win                      146534 non-null  float64
 10  teamScore                146536 non-null  int64
 11  opponentScore            146536 non-null  int64
 12  assists                  146532 non-null  float64
 13  blocks                   146532 non-null  float64
 14  steals                   146532 non-null  float64
 15  fieldGoalsAttempted      146532 non-null  float64
 16  fieldGoalsMade           146534 non-null  float64
 17  fieldGoalsPercentage     146532 non-null  float64
 18  threePointersAttempted   146532 non-null  float64
 19  threePointersMade        146532 non-null  float64
 20  threePointersPercentage  146531 non-null  float64
 21  freeThrowsAttempted      146532 non-null  float64
 22  freeThrowsMade           146534 non-null  float64
 23  freeThrowsPercentage     146532 non-null  float64
 24  reboundsDefensive        146532 non-null  float64
 25  reboundsOffensive        146532 non-null  float64
 26  reboundsTotal            146532 non-null  float64
 27  foulsPersonal            146532 non-null  float64
 28  turnovers                146532 non-null  float64
 29  plusMinusPoints          146479 non-null  float64
 30  numMinutes               146530 non-null  float64
 31  q1Points                 138688 non-null  float64
 32  q2Points                 138672 non-null  float64
 33  q3Points                 138638 non-null  float64
 34  q4Points                 138636 non-null  float64
 35  benchPoints              139226 non-null  float64
 36  biggestLead              139226 non-null  float64
 37  biggestScoringRun        139226 non-null  float64
 38  leadChanges              139226 non-null  float64
 39  pointsFastBreak          139226 non-null  float64
 40  pointsFromTurnovers      139226 non-null  float64
 41  pointsInThePaint         139226 non-null  float64
 42  pointsSecondChance       139226 non-null  float64
 43  timesTied                139226 non-null  float64
 44  timeoutsRemaining        139226 non-null  float64
 45  seasonWins               139226 non-null  float64
 46  seasonLosses             139226 non-null  float64
 47  coachId                  0 non-null       float64
 48  gameType                 138946 non-null  str
 49  gameLabel                9286 non-null    str
 50  gameSubLabel             9204 non-null    str
 51  seriesGameNumber         8854 non-null    float64
 52  seed                     7848 non-null    float64
 53  reboundsTeam             138946 non-null  float64
 54  turnoversTeam            138946 non-null  float64
 55  ot1Points                7816 non-null    float64
 56  ot2Points                1106 non-null    float64
 57  otAllPoints              7820 non-null    float64
 58  gameDate                 146536 non-null  str
dtypes: float64(44), int64(6), str(9)
memory usage: 66.0 MB

In [35]:
df["gameDateTimeEst"] = pd.to_datetime(df["gameDateTimeEst"])

In [36]:
df["gameDateTimeEst"].info()

<class 'pandas.Series'>
RangeIndex: 146536 entries, 0 to 146535
Series name: gameDateTimeEst
Non-Null Count   Dtype
--------------   -----
146536 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 1.1 MB

In [37]:
df = df.loc[df["gameDateTimeEst"] >= "1986-10-30 20:00:00"]

In [38]:
df.shape

(102704, 59)

In [39]:
df.sort_values(by="gameDateTimeEst")

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
102703,28600009,1986-10-31 20:00:00,Golden State,Warriors,1610612744,Phoenix,Suns,1610612756,0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102686,28600001,1986-10-31 20:00:00,Portland,Trail Blazers,1610612757,Seattle,SuperSonics,1610612760,1,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102687,28600001,1986-10-31 20:00:00,Seattle,SuperSonics,1610612760,Portland,Trail Blazers,1610612757,0,1.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102688,28600002,1986-10-31 20:00:00,Philadelphia,76ers,1610612755,Indiana,Pacers,1610612754,1,1.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102689,28600002,1986-10-31 20:00:00,Indiana,Pacers,1610612754,Philadelphia,76ers,1610612755,0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,42500301,2026-05-19 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 1,1.0,4.0,17.0,2.0,3.0,NaN,3.0,2026-05-19 20:00:00
3,42500312,2026-05-20 20:30:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,1,1.0,...,West Conf. Finals,Game 2,2.0,1.0,9.0,1.0,NaN,NaN,NaN,2026-05-20 20:30:00
2,42500312,2026-05-20 20:30:00,San Antonio,Spurs,1610612759,Oklahoma City,Thunder,1610612760,0,0.0,...,West Conf. Finals,Game 2,2.0,2.0,4.0,0.0,NaN,NaN,NaN,2026-05-20 20:30:00
1,42500302,2026-05-21 20:00:00,New York,Knicks,1610612752,Cleveland,Cavaliers,1610612739,1,1.0,...,East Conf. Finals,Game 2,2.0,3.0,14.0,2.0,NaN,NaN,NaN,2026-05-21 20:00:00
0,42500302,2026-05-21 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 2,2.0,4.0,11.0,0.0,NaN,NaN,NaN,2026-05-21 20:00:00

In [40]:
hornets_teams = df[df["teamName"] == "Hornets"]
hornets_teams["teamCity"].value_counts()

teamCity
Charlotte        2195
New Orleans       802
Oklahoma City     178
Name: count, dtype: int64

In [41]:
conditions = [
    (df['teamCity'] == 'Seattle') & (df['teamName'] == 'SuperSonics'),
    (df['teamCity'] == 'Washington') & (df['teamName'] == 'Bullets'),
    (df['teamCity'] == 'New Orleans') & (df['teamName'] == 'Hornets'),
    (df['teamCity'] == 'Oklahoma City') & (df['teamName'] == 'Hornets'),
    (df['teamCity'] == 'Charlotte') & (df['teamName'] == 'Bobcats'),
]

new_cities = ['Oklahoma City', 'Washington', 'New Orleans', 'New Orleans', 'Charlotte']
new_names = ['Thunder', 'Wizards', 'Pelicans', 'Pelicans', 'Hornets']

df['teamName'] = np.select(conditions, new_names, default=df['teamName'])

In [42]:
df = df.loc[:, "gameId":"turnovers"]

In [43]:
columns_to_drop = ["teamCity", "opponentTeamCity", "opponentTeamId", "opponentTeamName", "opponentScore"]
df = df.drop(columns=columns_to_drop)

In [44]:
df.shape

(102704, 24)

In [45]:
df.isna().sum()

gameId                     0
gameDateTimeEst            0
teamName                   2
teamId                     0
home                       0
win                        2
teamScore                  0
assists                    2
blocks                     2
steals                     2
fieldGoalsAttempted        2
fieldGoalsMade             2
fieldGoalsPercentage       2
threePointersAttempted     2
threePointersMade          2
threePointersPercentage    3
freeThrowsAttempted        2
freeThrowsMade             2
freeThrowsPercentage       2
reboundsDefensive          2
reboundsOffensive          2
reboundsTotal              2
foulsPersonal              2
turnovers                  2
dtype: int64

In [46]:
missing_rows = df[df.isna().any(axis=1)]
remove_games = missing_rows["gameId"].unique()
df = df.loc[~df["gameId"].isin(remove_games)]

In [47]:
df.isna().sum()

gameId                     0
gameDateTimeEst            0
teamName                   0
teamId                     0
home                       0
win                        0
teamScore                  0
assists                    0
blocks                     0
steals                     0
fieldGoalsAttempted        0
fieldGoalsMade             0
fieldGoalsPercentage       0
threePointersAttempted     0
threePointersMade          0
threePointersPercentage    0
freeThrowsAttempted        0
freeThrowsMade             0
freeThrowsPercentage       0
reboundsDefensive          0
reboundsOffensive          0
reboundsTotal              0
foulsPersonal              0
turnovers                  0
dtype: int64

In [48]:
df.teamName.value_counts()

teamName
Lakers            3752
Celtics           3710
Spurs             3686
Bulls             3622
Thunder           3619
Pacers            3619
Pistons           3606
Jazz              3603
Rockets           3586
Suns              3575
Cavaliers         3573
Mavericks         3570
Knicks            3564
Trail Blazers     3559
Warriors          3550
Hawks             3545
Nuggets           3542
76ers             3531
Bucks             3519
Heat              3489
Nets              3474
Clippers          3473
Kings             3422
Wizards           3419
Magic             3248
Timberwolves      3191
Hornets           3074
Raptors           2727
Grizzlies         2708
Pelicans          2120
Stripes              3
Stars                3
Loong-Lions          3
World                2
Team Vince           2
Team Melo            2
Team T-Mac           1
Team Austin          1
Phoenix              1
Jerusalem B.C.       1
United               1
Name: count, dtype: int64

In [53]:
count_teams = df.groupby("teamName")["teamName"].transform("count")
df = df[count_teams > 3]

In [56]:
df.teamName.value_counts()

teamName
Lakers           3752
Celtics          3710
Spurs            3686
Bulls            3622
Thunder          3619
Pacers           3619
Pistons          3606
Jazz             3603
Rockets          3586
Suns             3575
Cavaliers        3573
Mavericks        3570
Knicks           3564
Trail Blazers    3559
Warriors         3550
Hawks            3545
Nuggets          3542
76ers            3531
Bucks            3519
Heat             3489
Nets             3474
Clippers         3473
Kings            3422
Wizards          3419
Magic            3248
Timberwolves     3191
Hornets          3074
Raptors          2727
Grizzlies        2708
Pelicans         2120
Name: count, dtype: int64

In [57]:
df.head()

,gameId,gameDateTimeEst,teamName,teamId,home,win,teamScore,assists,blocks,steals,...,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers
0,42500302,2026-05-21 20:00:00,Cavaliers,1610612739,0,0.0,93,15.0,5.0,4.0,...,9.0,0.257,32.0,22.0,0.688,29.0,13.0,42.0,20.0,8.0
1,42500302,2026-05-21 20:00:00,Knicks,1610612752,1,1.0,109,32.0,5.0,5.0,...,13.0,0.361,14.0,8.0,0.571,35.0,5.0,40.0,22.0,6.0
2,42500312,2026-05-20 20:30:00,Spurs,1610612759,0,0.0,113,22.0,6.0,5.0,...,16.0,0.400,17.0,15.0,0.882,29.0,16.0,45.0,21.0,21.0
3,42500312,2026-05-20 20:30:00,Thunder,1610612760,1,1.0,122,34.0,3.0,14.0,...,13.0,0.361,24.0,19.0,0.792,24.0,17.0,41.0,21.0,9.0
4,42500301,2026-05-19 20:00:00,Cavaliers,1610612739,0,0.0,104,23.0,6.0,11.0,...,16.0,0.320,23.0,16.0,0.696,27.0,11.0,38.0,29.0,19.0