In [738]:
# Code to get the data

In [739]:
import pandas as pd
import numpy as np

In [740]:
# Data Cleaning

In [800]:
df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/TeamStatistics.csv")

In [801]:
df.head()

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
0,42500302,2026-05-21 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 2,2.0,4.0,11.0,0.0,NaN,NaN,NaN,2026-05-21 20:00:00
1,42500302,2026-05-21 20:00:00,New York,Knicks,1610612752,Cleveland,Cavaliers,1610612739,1,1.0,...,East Conf. Finals,Game 2,2.0,3.0,14.0,2.0,NaN,NaN,NaN,2026-05-21 20:00:00
2,42500312,2026-05-20 20:30:00,San Antonio,Spurs,1610612759,Oklahoma City,Thunder,1610612760,0,0.0,...,West Conf. Finals,Game 2,2.0,2.0,4.0,0.0,NaN,NaN,NaN,2026-05-20 20:30:00
3,42500312,2026-05-20 20:30:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,1,1.0,...,West Conf. Finals,Game 2,2.0,1.0,9.0,1.0,NaN,NaN,NaN,2026-05-20 20:30:00
4,42500301,2026-05-19 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 1,1.0,4.0,17.0,2.0,3.0,NaN,3.0,2026-05-19 20:00:00

In [743]:
df.shape

(146536, 59)

In [744]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 146536 entries, 0 to 146535
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gameId                   146536 non-null  int64
 1   gameDateTimeEst          146536 non-null  str
 2   teamCity                 146520 non-null  str
 3   teamName                 146534 non-null  str
 4   teamId                   146536 non-null  int64
 5   opponentTeamCity         146520 non-null  str
 6   opponentTeamName         146534 non-null  str
 7   opponentTeamId           146536 non-null  int64
 8   home                     146536 non-null  int64
 9   win                      146534 non-null  float64
 10  teamScore                146536 non-null  int64
 11  opponentScore            146536 non-null  int64
 12  assists                  146532 non-null  float64
 13  blocks                   146532 non-null  float64
 14  steals                   146532 non-null  float64
 15  fieldGoalsAttempted      146532 non-null  float64
 16  fieldGoalsMade           146534 non-null  float64
 17  fieldGoalsPercentage     146532 non-null  float64
 18  threePointersAttempted   146532 non-null  float64
 19  threePointersMade        146532 non-null  float64
 20  threePointersPercentage  146531 non-null  float64
 21  freeThrowsAttempted      146532 non-null  float64
 22  freeThrowsMade           146534 non-null  float64
 23  freeThrowsPercentage     146532 non-null  float64
 24  reboundsDefensive        146532 non-null  float64
 25  reboundsOffensive        146532 non-null  float64
 26  reboundsTotal            146532 non-null  float64
 27  foulsPersonal            146532 non-null  float64
 28  turnovers                146532 non-null  float64
 29  plusMinusPoints          146479 non-null  float64
 30  numMinutes               146530 non-null  float64
 31  q1Points                 138688 non-null  float64
 32  q2Points                 138672 non-null  float64
 33  q3Points                 138638 non-null  float64
 34  q4Points                 138636 non-null  float64
 35  benchPoints              139226 non-null  float64
 36  biggestLead              139226 non-null  float64
 37  biggestScoringRun        139226 non-null  float64
 38  leadChanges              139226 non-null  float64
 39  pointsFastBreak          139226 non-null  float64
 40  pointsFromTurnovers      139226 non-null  float64
 41  pointsInThePaint         139226 non-null  float64
 42  pointsSecondChance       139226 non-null  float64
 43  timesTied                139226 non-null  float64
 44  timeoutsRemaining        139226 non-null  float64
 45  seasonWins               139226 non-null  float64
 46  seasonLosses             139226 non-null  float64
 47  coachId                  0 non-null       float64
 48  gameType                 138946 non-null  str
 49  gameLabel                9286 non-null    str
 50  gameSubLabel             9204 non-null    str
 51  seriesGameNumber         8854 non-null    float64
 52  seed                     7848 non-null    float64
 53  reboundsTeam             138946 non-null  float64
 54  turnoversTeam            138946 non-null  float64
 55  ot1Points                7816 non-null    float64
 56  ot2Points                1106 non-null    float64
 57  otAllPoints              7820 non-null    float64
 58  gameDate                 146536 non-null  str
dtypes: float64(44), int64(6), str(9)
memory usage: 66.0 MB

In [745]:
df["gameDateTimeEst"] = pd.to_datetime(df["gameDateTimeEst"])

In [746]:
df["gameDateTimeEst"].info()

<class 'pandas.Series'>
RangeIndex: 146536 entries, 0 to 146535
Series name: gameDateTimeEst
Non-Null Count   Dtype
--------------   -----
146536 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 1.1 MB

In [747]:
df = df.loc[df["gameDateTimeEst"] >= "1986-10-30 20:00:00"]

In [748]:
df.shape

(102704, 59)

In [749]:
df.sort_values(by="gameDateTimeEst")

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
102703,28600009,1986-10-31 20:00:00,Golden State,Warriors,1610612744,Phoenix,Suns,1610612756,0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102686,28600001,1986-10-31 20:00:00,Portland,Trail Blazers,1610612757,Seattle,SuperSonics,1610612760,1,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102687,28600001,1986-10-31 20:00:00,Seattle,SuperSonics,1610612760,Portland,Trail Blazers,1610612757,0,1.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102688,28600002,1986-10-31 20:00:00,Philadelphia,76ers,1610612755,Indiana,Pacers,1610612754,1,1.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
102689,28600002,1986-10-31 20:00:00,Indiana,Pacers,1610612754,Philadelphia,76ers,1610612755,0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1986-10-31 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,42500301,2026-05-19 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 1,1.0,4.0,17.0,2.0,3.0,NaN,3.0,2026-05-19 20:00:00
3,42500312,2026-05-20 20:30:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,1,1.0,...,West Conf. Finals,Game 2,2.0,1.0,9.0,1.0,NaN,NaN,NaN,2026-05-20 20:30:00
2,42500312,2026-05-20 20:30:00,San Antonio,Spurs,1610612759,Oklahoma City,Thunder,1610612760,0,0.0,...,West Conf. Finals,Game 2,2.0,2.0,4.0,0.0,NaN,NaN,NaN,2026-05-20 20:30:00
1,42500302,2026-05-21 20:00:00,New York,Knicks,1610612752,Cleveland,Cavaliers,1610612739,1,1.0,...,East Conf. Finals,Game 2,2.0,3.0,14.0,2.0,NaN,NaN,NaN,2026-05-21 20:00:00
0,42500302,2026-05-21 20:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,0,0.0,...,East Conf. Finals,Game 2,2.0,4.0,11.0,0.0,NaN,NaN,NaN,2026-05-21 20:00:00

In [750]:
hornets_teams = df[df["teamName"] == "Hornets"]
hornets_teams["teamCity"].value_counts()

teamCity
Charlotte        2195
New Orleans       802
Oklahoma City     178
Name: count, dtype: int64

In [751]:
conditions = [
    (df['teamCity'] == 'Seattle') & (df['teamName'] == 'SuperSonics'),
    (df['teamCity'] == 'Washington') & (df['teamName'] == 'Bullets'),
    (df['teamCity'] == 'New Orleans') & (df['teamName'] == 'Hornets'),
    (df['teamCity'] == 'Oklahoma City') & (df['teamName'] == 'Hornets'),
    (df['teamCity'] == 'Charlotte') & (df['teamName'] == 'Bobcats'),
]

new_cities = ['Oklahoma City', 'Washington', 'New Orleans', 'New Orleans', 'Charlotte']
new_names = ['Thunder', 'Wizards', 'Pelicans', 'Pelicans', 'Hornets']

df['teamName'] = np.select(conditions, new_names, default=df['teamName'])

In [752]:
df = df.loc[:, "gameId":"turnovers"]

In [753]:
columns_to_drop = ["teamCity", "opponentTeamCity", "opponentTeamId", "opponentTeamName"]
df = df.drop(columns=columns_to_drop)

In [754]:
df.shape

(102704, 25)

In [755]:
df.isna().sum()

gameId                     0
gameDateTimeEst            0
teamName                   2
teamId                     0
home                       0
win                        2
teamScore                  0
opponentScore              0
assists                    2
blocks                     2
steals                     2
fieldGoalsAttempted        2
fieldGoalsMade             2
fieldGoalsPercentage       2
threePointersAttempted     2
threePointersMade          2
threePointersPercentage    3
freeThrowsAttempted        2
freeThrowsMade             2
freeThrowsPercentage       2
reboundsDefensive          2
reboundsOffensive          2
reboundsTotal              2
foulsPersonal              2
turnovers                  2
dtype: int64

In [756]:
missing_rows = df[df.isna().any(axis=1)]
remove_games = missing_rows["gameId"].unique()
df = df.loc[~df["gameId"].isin(remove_games)]

In [757]:
df.isna().sum()

gameId                     0
gameDateTimeEst            0
teamName                   0
teamId                     0
home                       0
win                        0
teamScore                  0
opponentScore              0
assists                    0
blocks                     0
steals                     0
fieldGoalsAttempted        0
fieldGoalsMade             0
fieldGoalsPercentage       0
threePointersAttempted     0
threePointersMade          0
threePointersPercentage    0
freeThrowsAttempted        0
freeThrowsMade             0
freeThrowsPercentage       0
reboundsDefensive          0
reboundsOffensive          0
reboundsTotal              0
foulsPersonal              0
turnovers                  0
dtype: int64

In [791]:
df.teamName.value_counts()

teamName
Lakers           3752
Celtics          3710
Spurs            3686
Bulls            3622
Thunder          3619
Pacers           3619
Pistons          3606
Jazz             3603
Rockets          3586
Suns             3575
Cavaliers        3573
Mavericks        3570
Knicks           3564
Trail Blazers    3559
Warriors         3550
Hawks            3545
Nuggets          3542
76ers            3531
Bucks            3519
Heat             3489
Nets             3474
Clippers         3473
Kings            3422
Wizards          3419
Magic            3248
Timberwolves     3191
Hornets          3074
Raptors          2727
Grizzlies        2708
Pelicans         2120
Name: count, dtype: int64

In [759]:
count_teams = df.groupby("teamName")["teamName"].transform("count")
df = df[count_teams > 3]

In [790]:
df.teamName.value_counts()

teamName
Lakers           3752
Celtics          3710
Spurs            3686
Bulls            3622
Thunder          3619
Pacers           3619
Pistons          3606
Jazz             3603
Rockets          3586
Suns             3575
Cavaliers        3573
Mavericks        3570
Knicks           3564
Trail Blazers    3559
Warriors         3550
Hawks            3545
Nuggets          3542
76ers            3531
Bucks            3519
Heat             3489
Nets             3474
Clippers         3473
Kings            3422
Wizards          3419
Magic            3248
Timberwolves     3191
Hornets          3074
Raptors          2727
Grizzlies        2708
Pelicans         2120
Name: count, dtype: int64

In [761]:
df = df.rename(columns={"teamScore": "points"})

In [762]:
game_counts = df["gameId"].value_counts()
broken_games = game_counts[game_counts != 2]
missing_game_ids = list(broken_games.index)
print(missing_game_ids)

[12500055, 12500043, 12500032, 12500011, 12500026, 12500009]

In [ ]:
df[df["gameId"].isin(missing_game_ids)]

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,assists,blocks,...,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers
2685,12500055,2025-10-13 20:00:00,Timberwolves,1610612750,1,1.0,134,74,34.0,5.0,...,17.0,0.515,22.0,17.0,0.773,40.0,12.0,52.0,19.0,16.0
2722,12500043,2025-10-09 22:30:00,Clippers,1610612746,1,1.0,142,95,42.0,10.0,...,21.0,0.488,25.0,17.0,0.680,34.0,12.0,46.0,28.0,16.0
2755,12500032,2025-10-06 20:00:00,Spurs,1610612759,1,1.0,119,88,31.0,8.0,...,15.0,0.395,24.0,18.0,0.750,37.0,15.0,52.0,24.0,23.0
2762,12500011,2025-10-04 23:00:00,Pelicans,1610612740,1,1.0,127,92,33.0,8.0,...,12.0,0.364,33.0,23.0,0.697,38.0,12.0,50.0,21.0,16.0
2766,12500026,2025-10-04 20:00:00,Nets,1610612751,1,1.0,123,88,31.0,4.0,...,17.0,0.447,16.0,8.0,0.500,37.0,15.0,52.0,28.0,15.0
2774,12500009,2025-10-03 05:30:00,Pelicans,1610612740,1,1.0,107,97,20.0,8.0,...,8.0,0.242,24.0,19.0,0.792,33.0,13.0,46.0,22.0,16.0

In [792]:
df = df[~df["gameId"].isin(missing_game_ids)]

In [793]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating
0,28600001,1986-10-31 20:00:00,Thunder,1610612760,0,1.0,127,110,102.2976,0.622093,0.224834,0.448276,0.279070,124.147585,107.529404,16.618181
1,28600001,1986-10-31 20:00:00,Trail Blazers,1610612757,1,0.0,110,127,100.1088,0.506494,0.199783,0.272727,0.480519,109.880450,126.861974,-16.981524
2,28600002,1986-10-31 20:00:00,Pacers,1610612754,0,0.0,104,108,94.4640,0.469880,0.148205,0.318182,0.421687,110.094851,114.329268,-4.234417
3,28600002,1986-10-31 20:00:00,76ers,1610612755,1,1.0,108,104,100.0320,0.523810,0.249920,0.461538,0.357143,107.965451,103.966731,3.998720
4,28600003,1986-10-31 20:00:00,Wizards,1610612764,0,0.0,102,120,98.7264,0.435294,0.222838,0.400000,0.423529,103.315830,121.548036,-18.232205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102671,42500301,2026-05-19 20:00:00,Knicks,1610612752,1,1.0,115,104,105.6768,0.534091,0.160868,0.250000,0.363636,108.822372,98.413275,10.409096
102672,42500312,2026-05-20 20:30:00,Spurs,1610612759,0,0.0,113,122,92.6208,0.583333,0.226731,0.400000,0.202381,122.002833,131.719873,-9.717040
102673,42500312,2026-05-20 20:30:00,Thunder,1610612760,1,1.0,122,113,92.6976,0.547872,0.097090,0.369565,0.255319,131.610743,121.901754,9.708989
102674,42500302,2026-05-21 20:00:00,Cavaliers,1610612739,0,0.0,93,109,85.5168,0.443750,0.093549,0.270833,0.400000,108.750561,127.460335,-18.709774
102675,42500302,2026-05-21 20:00:00,Knicks,1610612752,1,1.0,109,93,88.4736,0.594118,0.067817,0.147059,0.164706,123.200593,105.116102,18.084491

In [765]:
# Calculate single game features

In [766]:
def shift_opponent_stats(df):
    df = df.sort_values(by=["gameDateTimeEst", "gameId", "home"])

    opp_map = df[["gameId", "home", "reboundsDefensive"]].copy()
    
    opp_map["home"] = opp_map["home"].replace({1: 0, 0: 1})
    
    opp_map = opp_map.rename(columns={
        "reboundsDefensive": "opp_dreb"
    })
    
    df = pd.merge(df, opp_map, on=["gameId", "home"], how="left")

    return df

In [767]:
def create_four_factors(df):

    df["possessions"] = .96 * (df["fieldGoalsAttempted"] + df["turnovers"] + .44 * df["freeThrowsAttempted"] - df["reboundsOffensive"])

    df["eFG"] = (df["fieldGoalsMade"] + .5 * df["threePointersMade"]) / df["fieldGoalsAttempted"]

    df["TO%"] = df["turnovers"] / df["possessions"]

    df["OREB%"] = (df["reboundsOffensive"]) / (df["reboundsOffensive"] + df["opp_dreb"])

    df["FTR"] = df["freeThrowsAttempted"] / df["fieldGoalsAttempted"]

    df = df.drop(columns=df.loc[:,"assists":"opp_dreb"].columns)

    return df

In [768]:
def team_rating(df):
    df["off_rating"] = (df["points"] / df["possessions"]) * 100
    df["def_rating"] = (df["opponentScore"] / df["possessions"]) * 100
    df["net_rating"] = df["off_rating"] - df["def_rating"]
    return df

In [769]:
df = shift_opponent_stats(df)
df = create_four_factors(df)
df = team_rating(df)

In [770]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating
0,28600001,1986-10-31 20:00:00,Thunder,1610612760,0,1.0,127,110,102.2976,0.622093,0.224834,0.448276,0.279070,124.147585,107.529404,16.618181
1,28600001,1986-10-31 20:00:00,Trail Blazers,1610612757,1,0.0,110,127,100.1088,0.506494,0.199783,0.272727,0.480519,109.880450,126.861974,-16.981524
2,28600002,1986-10-31 20:00:00,Pacers,1610612754,0,0.0,104,108,94.4640,0.469880,0.148205,0.318182,0.421687,110.094851,114.329268,-4.234417
3,28600002,1986-10-31 20:00:00,76ers,1610612755,1,1.0,108,104,100.0320,0.523810,0.249920,0.461538,0.357143,107.965451,103.966731,3.998720
4,28600003,1986-10-31 20:00:00,Wizards,1610612764,0,0.0,102,120,98.7264,0.435294,0.222838,0.400000,0.423529,103.315830,121.548036,-18.232205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102671,42500301,2026-05-19 20:00:00,Knicks,1610612752,1,1.0,115,104,105.6768,0.534091,0.160868,0.250000,0.363636,108.822372,98.413275,10.409096
102672,42500312,2026-05-20 20:30:00,Spurs,1610612759,0,0.0,113,122,92.6208,0.583333,0.226731,0.400000,0.202381,122.002833,131.719873,-9.717040
102673,42500312,2026-05-20 20:30:00,Thunder,1610612760,1,1.0,122,113,92.6976,0.547872,0.097090,0.369565,0.255319,131.610743,121.901754,9.708989
102674,42500302,2026-05-21 20:00:00,Cavaliers,1610612739,0,0.0,93,109,85.5168,0.443750,0.093549,0.270833,0.400000,108.750561,127.460335,-18.709774
102675,42500302,2026-05-21 20:00:00,Knicks,1610612752,1,1.0,109,93,88.4736,0.594118,0.067817,0.147059,0.164706,123.200593,105.116102,18.084491

In [771]:
# Calculate elo for each team

In [772]:
raw_elo_df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/nbaallelo.csv")

In [773]:
raw_elo_df.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

In [774]:
raw_elo_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameorder      126314 non-null  int64
 1   game_id        126314 non-null  str
 2   lg_id          126314 non-null  str
 3   _iscopy        126314 non-null  int64
 4   year_id        126314 non-null  int64
 5   date_game      126314 non-null  str
 6   seasongame     126314 non-null  int64
 7   is_playoffs    126314 non-null  int64
 8   team_id        126314 non-null  str
 9   fran_id        126314 non-null  str
 10  pts            126314 non-null  int64
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  str
 15  opp_fran       126314 non-null  str
 16  opp_pts        126314 non-null  int64
 17  opp_elo_i      126314 non-null  float64
 18  opp_elo_n      126314 non-null  float64
 19  game_location  126314 non-null  str
 20  game_result    126314 non-null  str
 21  forecast       126314 non-null  float64
 22  notes          5424 non-null    str
dtypes: float64(6), int64(7), str(10)
memory usage: 22.2 MB

In [775]:
raw_elo_df["date_game"] = pd.to_datetime(raw_elo_df["date_game"])

In [776]:
elo_df = raw_elo_df[(raw_elo_df["date_game"] >= "10/31/1986") & (raw_elo_df["date_game"] <= "11/1/1986")]

In [777]:
first_game_elo_df = elo_df.drop_duplicates(subset=["fran_id"], keep="first")[["fran_id", "elo_i"]]

In [778]:
first_game_elo_df["fran_id"].sort_values().unique()

<StringArray>
[       'Bucks',        'Bulls',    'Cavaliers',      'Celtics',
     'Clippers',        'Hawks',         'Jazz',        'Kings',
       'Knicks',       'Lakers',    'Mavericks',         'Nets',
      'Nuggets',       'Pacers',      'Pistons',      'Rockets',
       'Sixers',        'Spurs',         'Suns',      'Thunder',
 'Trailblazers',     'Warriors',      'Wizards']
Length: 23, dtype: str

In [779]:
first_game_elo_df["fran_id"] = first_game_elo_df["fran_id"].replace({"Sixers":"76ers","Trailblazers":"Trail Blazers"})

In [780]:
first_game_elo_df["fran_id"].sort_values().unique()

<StringArray>
[        '76ers',         'Bucks',         'Bulls',     'Cavaliers',
       'Celtics',      'Clippers',         'Hawks',          'Jazz',
         'Kings',        'Knicks',        'Lakers',     'Mavericks',
          'Nets',       'Nuggets',        'Pacers',       'Pistons',
       'Rockets',         'Spurs',          'Suns',       'Thunder',
 'Trail Blazers',      'Warriors',       'Wizards']
Length: 23, dtype: str

In [781]:
df["teamName"].sort_values().unique()

<StringArray>
[        '76ers',         'Bucks',         'Bulls',     'Cavaliers',
       'Celtics',      'Clippers',     'Grizzlies',         'Hawks',
          'Heat',       'Hornets',          'Jazz',         'Kings',
        'Knicks',        'Lakers',         'Magic',     'Mavericks',
          'Nets',       'Nuggets',        'Pacers',      'Pelicans',
       'Pistons',       'Raptors',       'Rockets',         'Spurs',
          'Suns',       'Thunder',  'Timberwolves', 'Trail Blazers',
      'Warriors',       'Wizards']
Length: 30, dtype: str

In [782]:
new_teams_elo = [
    {"fran_id": "Heat", "elo_i":"1300"},
    {"fran_id": "Hornets", "elo_i":"1300"},
    {"fran_id": "Magic", "elo_i":"1300"},
    {"fran_id": "Timberwolves", "elo_i":"1300"},
    {"fran_id": "Raptors", "elo_i":"1300"},
    {"fran_id": "Grizzlies", "elo_i":"1300"},
    {"fran_id": "Pelicans", "elo_i":"1300"},
]

df_new_teams_elo = pd.DataFrame(new_teams_elo)

In [783]:
full_elo_df = pd.concat([first_game_elo_df, df_new_teams_elo], ignore_index=True)

In [784]:
full_elo_df

          fran_id      elo_i
0         Wizards  1478.1702
1         Celtics  1726.8047
2       Mavericks  1547.2805
3            Jazz  1508.7253
4           Spurs    1414.76
5         Nuggets  1514.6084
6         Pistons  1532.8929
7           Bucks  1613.2163
8            Nets  1470.3269
9          Knicks  1362.9786
10         Pacers  1433.3845
11          76ers  1590.3137
12       Warriors  1447.6735
13           Suns  1444.3523
14  Trail Blazers  1482.1389
15        Thunder  1451.3865
16          Kings   1461.196
17       Clippers  1424.3226
18          Hawks  1567.9272
19      Cavaliers  1443.2375
20         Lakers  1611.3174
21        Rockets   1611.462
22          Bulls  1436.9487
23           Heat       1300
24        Hornets       1300
25          Magic       1300
26   Timberwolves       1300
27        Raptors       1300
28      Grizzlies       1300
29       Pelicans       1300

In [785]:
starting_elo = dict(zip(full_elo_df["fran_id"],full_elo_df["elo_i"]))

In [786]:
starting_elo

{'Wizards': 1478.1702,
 'Celtics': 1726.8047,
 'Mavericks': 1547.2805,
 'Jazz': 1508.7253,
 'Spurs': 1414.76,
 'Nuggets': 1514.6084,
 'Pistons': 1532.8929,
 'Bucks': 1613.2163,
 'Nets': 1470.3269,
 'Knicks': 1362.9786,
 'Pacers': 1433.3845,
 '76ers': 1590.3137,
 'Warriors': 1447.6735,
 'Suns': 1444.3523,
 'Trail Blazers': 1482.1389,
 'Thunder': 1451.3865,
 'Kings': 1461.196,
 'Clippers': 1424.3226,
 'Hawks': 1567.9272,
 'Cavaliers': 1443.2375,
 'Lakers': 1611.3174,
 'Rockets': 1611.462,
 'Bulls': 1436.9487,
 'Heat': '1300',
 'Hornets': '1300',
 'Magic': '1300',
 'Timberwolves': '1300',
 'Raptors': '1300',
 'Grizzlies': '1300',
 'Pelicans': '1300'}

In [797]:
starting_elo_df = pd.DataFrame(starting_elo, index=[0])

In [798]:
starting_elo_df.to_csv("starting_elo.csv", index=False)

In [799]:
df.to_csv("cleaned_data.csv")