In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/nba_2008-2025.csv")

In [4]:
df.isna().sum()

season               0
date                 0
regular              0
playoffs             0
away                 0
home                 0
score_away           0
score_home           0
q1_away              0
q2_away              0
q3_away              0
q4_away              0
ot_away              0
q1_home              0
q2_home              0
q3_home              0
q4_home              0
ot_home              0
whos_favored         0
spread               3
total                0
moneyline_away    3298
moneyline_home    3298
h2_spread         3296
h2_total          3301
id_spread            3
id_total             0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19812 entries, 0 to 19821
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          19812 non-null  int64
 1   date            19812 non-null  object
 2   regular         19812 non-null  bool
 3   playoffs        19812 non-null  bool
 4   away            19812 non-null  object
 5   home            19812 non-null  object
 6   score_away      19812 non-null  int64
 7   score_home      19812 non-null  int64
 8   q1_away         19812 non-null  int64
 9   q2_away         19812 non-null  int64
 10  q3_away         19812 non-null  int64
 11  q4_away         19812 non-null  int64
 12  ot_away         19812 non-null  int64
 13  q1_home         19812 non-null  int64
 14  q2_home         19812 non-null  int64
 15  q3_home         19812 non-null  int64
 16  q4_home         19812 non-null  int64
 17  ot_home         19812 non-null  int64
 18  whos_favored    19812 non-null  object
 19  spread          19812 non-null  float64
 20  total           19812 non-null  float64
 21  moneyline_away  19812 non-null  float64
 22  moneyline_home  19812 non-null  float64
 23  h2_spread       19812 non-null  float64
 24  h2_total        19812 non-null  float64
 25  id_spread       19812 non-null  float64
 26  id_total        19812 non-null  int64
dtypes: bool(2), float64(7), int64(14), object(4)
memory usage: 4.0+ MB

In [7]:
df["date"] = pd.to_datetime(df["date"])

In [8]:
df = df[df["date"] >= "2012-7-30"]

In [9]:
df = df[["season", "date", "away", "home", "moneyline_away", "moneyline_home", "score_away", "score_home"]]

In [10]:
df.sort_values(by="date", ascending=False)

,season,date,away,home,moneyline_away,moneyline_home,score_away,score_home
19821,2023,2023-01-16,hou,lal,240.0,-280.0,132,140
19820,2023,2023-01-16,phx,mem,550.0,-800.0,106,136
19819,2023,2023-01-16,utah,min,155.0,-175.0,126,125
19818,2023,2023-01-16,mia,atl,-105.0,-115.0,113,121
19817,2023,2023-01-16,gs,wsh,-140.0,120.0,127,118
...,...,...,...,...,...,...,...,...
6338,2013,2012-10-31,mem,lac,155.0,-175.0,92,101
6339,2013,2012-10-31,lal,por,-135.0,115.0,106,116
6330,2013,2012-10-30,dal,lal,400.0,-500.0,99,91
6329,2013,2012-10-30,bos,mia,240.0,-280.0,107,120
6328,2013,2012-10-30,wsh,cle,210.0,-250.0,84,94

In [11]:
df["away"].unique()

array(['wsh', 'bos', 'dal', 'ind', 'den', 'hou', 'sa', 'sac', 'gs', 'mem',
       'lal', 'okc', 'mil', 'chi', 'utah', 'por', 'mia', 'det', 'lac',
       'tor', 'no', 'cha', 'cle', 'phi', 'min', 'phx', 'atl', 'ny', 'orl',
       'bkn'], dtype=object)

In [12]:
team_mapping = {
    'Trail Blazers': 'por',
    'Jazz': 'utah',
    'Rockets': 'hou',
    '76ers': 'phi',
    'Wizards': 'wsh',
    'Bucks': 'mil',
    'Bulls': 'chi',
    'Mavericks': 'dal',
    'Spurs': 'sa',
    'Kings': 'sac',
    'Thunder': 'okc',
    'Pistons': 'det',
    'Suns': 'phx',
    'Heat': 'mia',
    'Raptors': 'tor',
    'Knicks': 'ny',
    'Nuggets': 'den',
    'Lakers': 'lal',
    'Warriors': 'gs',
    'Nets': 'bkn',
    'Magic': 'orl',
    'Pacers': 'ind',
    'Celtics': 'bos',
    'Timberwolves': 'min',
    'Hornets': 'cha',
    'Hawks': 'atl',
    'Pelicans': 'no',
    'Cavaliers': 'cle',
    'Clippers': 'lac',
    'Grizzlies': 'mem'
}

In [13]:
inv_team_mapping = {v: k for k, v in team_mapping.items()}
df['away'] = df['away'].map(inv_team_mapping)
df['home'] = df['home'].map(inv_team_mapping)

In [14]:
df["away"].unique()

array(['Wizards', 'Celtics', 'Mavericks', 'Pacers', 'Nuggets', 'Rockets',
       'Spurs', 'Kings', 'Warriors', 'Grizzlies', 'Lakers', 'Thunder',
       'Bucks', 'Bulls', 'Jazz', 'Trail Blazers', 'Heat', 'Pistons',
       'Clippers', 'Raptors', 'Pelicans', 'Hornets', 'Cavaliers', '76ers',
       'Timberwolves', 'Suns', 'Hawks', 'Knicks', 'Magic', 'Nets'],
      dtype=object)

In [15]:
full_advanced_metrics_df = pd.read_csv("../data/final_dataset.csv", index_col=0)
full_advanced_metrics_df["game_date"] = pd.to_datetime(full_advanced_metrics_df["game_date"])

In [16]:
advanced_metrics_df = full_advanced_metrics_df[(full_advanced_metrics_df.game_date >= "2012-7-30") & (full_advanced_metrics_df.game_date <= "2023-01-17")]

In [17]:
advanced_metrics_df

,game_date,teamName_home,teamName_away,pre_game_elo_home,is_B2B_home,pre_game_elo_away,is_B2B_away,pre_game_elo_diff,days_rest_diff,possessions_rolling_diff,eFG_rolling_diff,TO%_rolling_diff,OREB%_rolling_diff,FTR_rolling_diff,off_rating_rolling_diff,def_rating_rolling_diff,net_rating_rolling_diff,win_home
0,2012-11-02 19:30:00,Cavaliers,Bulls,1358.433045,False,1598.996440,False,-240.563396,1.0,-5.606400,0.069620,0.046333,0.135957,-0.139241,7.464050,2.511008,4.953042,False
1,2012-11-02 20:00:00,Pelicans,Jazz,1449.507674,False,1543.709558,False,-94.201884,0.0,-5.145600,0.001826,0.018851,-0.170330,-0.184410,-13.038751,10.799130,-23.837881,True
2,2012-11-02 20:00:00,Thunder,Trail Blazers,1655.963612,True,1461.615835,False,194.347777,-1.0,-4.032000,-0.138163,0.072911,0.016667,-0.038648,-30.196067,-17.255290,-12.940778,True
3,2012-11-02 22:00:00,Suns,Pistons,1522.039056,False,1420.973704,False,101.065351,0.0,0.230400,-0.056013,0.021120,0.023256,-0.054114,-12.109219,-19.675414,7.566195,True
4,2012-11-02 22:30:00,Warriors,Grizzlies,1429.322844,False,1571.393699,False,-142.070854,0.0,-5.836800,0.017442,-0.018907,-0.014167,-0.081395,0.450640,-10.778775,11.229415,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12140,2023-01-16 15:00:00,Wizards,Warriors,1487.499662,False,1501.977836,True,-14.478174,2.0,-5.182671,-0.025275,-0.007886,-0.008915,0.044782,-2.919427,-2.539484,-0.379943,False
12141,2023-01-16 15:30:00,Hawks,Heat,1491.574489,False,1533.373416,False,-41.798927,0.0,5.661170,0.021529,-0.019037,-0.103701,-0.021127,-1.198133,4.479981,-5.678115,True
12142,2023-01-16 16:00:00,Timberwolves,Jazz,1484.919750,False,1517.671835,False,-32.752085,0.0,-2.167485,0.044116,0.009749,-0.075077,-0.054299,-0.054571,-2.178265,2.123694,False
12143,2023-01-16 18:00:00,Grizzlies,Suns,1631.647091,False,1502.323922,False,129.323169,-1.0,5.901115,0.042120,-0.040087,0.014876,0.054927,11.249612,-6.847753,18.097365,True
12144,2023-01-16 22:30:00,Lakers,Rockets,1511.935285,True,1324.867227,True,187.068058,0.0,3.007974,0.043848,-0.024473,-0.045153,-0.008867,7.984984,-6.952121,14.937105,True

In [18]:
advanced_metrics_df["date_normalized"] = advanced_metrics_df["game_date"].dt.normalize()

/var/folders/dp/qtk9dsts67s5v6gg3dqp94200000gn/T/ipykernel_4800/1830112880.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics_df["date_normalized"] = advanced_metrics_df["game_date"].dt.normalize()

In [19]:
advanced_metrics_df

,game_date,teamName_home,teamName_away,pre_game_elo_home,is_B2B_home,pre_game_elo_away,is_B2B_away,pre_game_elo_diff,days_rest_diff,possessions_rolling_diff,eFG_rolling_diff,TO%_rolling_diff,OREB%_rolling_diff,FTR_rolling_diff,off_rating_rolling_diff,def_rating_rolling_diff,net_rating_rolling_diff,win_home,date_normalized
0,2012-11-02 19:30:00,Cavaliers,Bulls,1358.433045,False,1598.996440,False,-240.563396,1.0,-5.606400,0.069620,0.046333,0.135957,-0.139241,7.464050,2.511008,4.953042,False,2012-11-02
1,2012-11-02 20:00:00,Pelicans,Jazz,1449.507674,False,1543.709558,False,-94.201884,0.0,-5.145600,0.001826,0.018851,-0.170330,-0.184410,-13.038751,10.799130,-23.837881,True,2012-11-02
2,2012-11-02 20:00:00,Thunder,Trail Blazers,1655.963612,True,1461.615835,False,194.347777,-1.0,-4.032000,-0.138163,0.072911,0.016667,-0.038648,-30.196067,-17.255290,-12.940778,True,2012-11-02
3,2012-11-02 22:00:00,Suns,Pistons,1522.039056,False,1420.973704,False,101.065351,0.0,0.230400,-0.056013,0.021120,0.023256,-0.054114,-12.109219,-19.675414,7.566195,True,2012-11-02
4,2012-11-02 22:30:00,Warriors,Grizzlies,1429.322844,False,1571.393699,False,-142.070854,0.0,-5.836800,0.017442,-0.018907,-0.014167,-0.081395,0.450640,-10.778775,11.229415,False,2012-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12140,2023-01-16 15:00:00,Wizards,Warriors,1487.499662,False,1501.977836,True,-14.478174,2.0,-5.182671,-0.025275,-0.007886,-0.008915,0.044782,-2.919427,-2.539484,-0.379943,False,2023-01-16
12141,2023-01-16 15:30:00,Hawks,Heat,1491.574489,False,1533.373416,False,-41.798927,0.0,5.661170,0.021529,-0.019037,-0.103701,-0.021127,-1.198133,4.479981,-5.678115,True,2023-01-16
12142,2023-01-16 16:00:00,Timberwolves,Jazz,1484.919750,False,1517.671835,False,-32.752085,0.0,-2.167485,0.044116,0.009749,-0.075077,-0.054299,-0.054571,-2.178265,2.123694,False,2023-01-16
12143,2023-01-16 18:00:00,Grizzlies,Suns,1631.647091,False,1502.323922,False,129.323169,-1.0,5.901115,0.042120,-0.040087,0.014876,0.054927,11.249612,-6.847753,18.097365,True,2023-01-16
12144,2023-01-16 22:30:00,Lakers,Rockets,1511.935285,True,1324.867227,True,187.068058,0.0,3.007974,0.043848,-0.024473,-0.045153,-0.008867,7.984984,-6.952121,14.937105,True,2023-01-16

In [20]:
df = df.rename(columns={"date": "date_normalized", "away": "teamName_away", "home": "teamName_home"})

In [21]:
df = df[["date_normalized", "teamName_home", "teamName_away", "moneyline_home", "moneyline_away"]]

In [22]:
final_df = pd.merge(advanced_metrics_df, df, on=["date_normalized", "teamName_away", "teamName_home"], how="left")

In [23]:
final_df["moneyline_home"].isna().sum()

np.int64(5)

In [24]:
final_df.loc[9268, ["moneyline_home", "moneyline_away"]] = [360, -500]
final_df.loc[9591, ["moneyline_home", "moneyline_away"]] = [-240, 190]
final_df.loc[10166, ["moneyline_home", "moneyline_away"]] = [-190, 170]
final_df.loc[10238, ["moneyline_home", "moneyline_away"]] = [-105, -115]
final_df.loc[10255, ["moneyline_home", "moneyline_away"]] = [235, -275]

In [25]:
final_df.isna().sum()

game_date                   0
teamName_home               0
teamName_away               0
pre_game_elo_home           0
is_B2B_home                 0
pre_game_elo_away           0
is_B2B_away                 0
pre_game_elo_diff           0
days_rest_diff              0
possessions_rolling_diff    0
eFG_rolling_diff            0
TO%_rolling_diff            0
OREB%_rolling_diff          0
FTR_rolling_diff            0
off_rating_rolling_diff     0
def_rating_rolling_diff     0
net_rating_rolling_diff     0
win_home                    0
date_normalized             0
moneyline_home              0
moneyline_away              0
dtype: int64

In [26]:
def convert_american_to_implied(odds):
    """
    Converts American odds (e.g., -150, +130) to implied probabilities.
    """
    return np.where(odds < 0, 
                    abs(odds) / (abs(odds) + 100), 
                    100 / (odds + 100))

# vegas_odds['home_implied'] = convert_american_to_implied(vegas_odds['moneyline_home'])
# vegas_odds['away_implied'] = convert_american_to_implied(vegas_odds['moneyline_away'])